export const RouterStore = {
    website: {
        index: '/',
        settings: '/settings/',
        login: '/login/',
        signup: '/signup/',
        album: '/album/:title/',
        artist: '/artist/:title/',
        favorite: '/favorite/',
        playlists: '/playlists/',
        playlist: '/playlist/:id/',
        search: '/search/',
        radio: '/radio/',
        profile: '/profile/:nickname',
    },
    api: {
        user: {
            current: '/api/v1/user',
            login: '/api/v1/session',
            register: '/api/v1/user',
            logout: '/api/v1/session',
            change: {
                avatar: '/api/v1/user/photo',
                profile: '/api/v1/user/profile',
                password: '/api/v1/user/password',
            },
            profile: '/api/v1/user/:nickname/profile',
            getSubs: '/api/v1/user/:nickname/subscriptions',
            follow: '/api/v1/user/:nickname/subscription',
        },
        artist: {
            list: '/api/v1/artists',
            current: '/api/v1/artists/:slug',
        },
        albums: {
            current: '/api/v1/albums/:id',
            indexList: '/api/v1/albums?count=:count&from=:from',
            artist: '/api/v1/artists/:id/albums',
        },
        track: {
            all: '/api/v1/track',
            update: '/api/v1/tracks/:id',
            add: '/api/v1/tracks',
            delete: '/api/v1/tracks/:id',
            artist: '/api/v1/artists/:id/tracks',
            index: '/api/v1/tracks?count=:count&from=:from',
            favorite: {
                list: '/api/v1/favorite/tracks',
                add: '/api/v1/favorite/track/:id',
            },
            like: '/api/v1/tracks/:id/like',
        },
        playlists: {
            list: '/api/v1/playlists',
            current: '/api/v1/playlists/:id',
            add: '/api/v1/playlists/:id/tracks',
            remove: '/api/v1/playlists/:id/tracks/:track_id',
            poster: '/api/v1/playlists/:id/photo',
            create: '/api/v1/playlists',
            delete: '/api/v1/playlists/:id',
        },
        search: {
            all: '/api/v1/search?query=:query&offset=:offset&limit=:limit',
        },
    },
};
